explore/urls.py
from django.urls import path
from . import views

app_name = 'explore'

urlpatterns = [
    path('', views.list, name='webpage_list'),
    path('<slug:category_slug>/', views.list, name='webpage_list_by_category'),
]

thoughts/urls.py
from django.urls import path
from . import views

app_name = 'thoughts'

urlpatterns = [
    path('', views.post_list, name="post_list")
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('home/', views.home_view, name="home"),
    path('explore/', include("explore.urls", namespace="explore")),
    path('about/', views.about, name="about"),
    path('complaints/', views.complaints, name="complaints"),
    path('thoughts/', include("thoughts.urls", namespace="thoughts")),
    path('in-progress/', views.in_progress, name="in-progress")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explore/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse("explore:webpage_list_by_category", args=[self.slug])
    
    
class WebPage(models.Model):
    category = models.ManyToManyField(Category, related_name='webpages', blank=True)

    name = models.CharField(max_length=100, db_index=True)
    link = models.CharField(max_length=500, db_index=True)
    description = models.CharField(max_length=200)
    
    likes = models.IntegerField(default=0)
    
    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
    def get_description(self):
        return self.description

thoughts/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.CharField(max_length=250, default="Anonymous") # author name
    publish = models.DateTimeField(default=timezone.now)
    body = models.TextField()

    class Meta:
        ordering = ('-publish',)

    def __str__(self) -> str:
        return self.title

thoughts/forms.py
from .models import Post
from django import forms

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','author', 'body')

explore/views.py
from django.shortcuts import render, get_object_or_404
from explore.models import WebPage, Category
from django.http import JsonResponse
from django.template.loader import render_to_string
# Create your views here.

def list(request, category_slug=None):
    category = None # default none
    
    webpages = WebPage.objects.all()

    url_parameter = request.GET.get("q")

    '''
    Filtering the categories by search
    '''
    if url_parameter:
        categories = Category.objects.filter(name__icontains=url_parameter)
    else:
        categories = Category.objects.all()
    

    '''
    Getting webpages based on the category selected
    '''
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        webpages = WebPage.objects.filter(category=category)

    does_req_accept_json = request.accepts("application/json")
    is_ajax_request = request.headers.get("x-requested-with") == "XMLHttpRequest" and does_req_accept_json

    if is_ajax_request:
        html = render_to_string(
            template_name="explore/categories-results-partial.html",
            context={"categories":categories}
        )

        data_dict = {"html_from_view": html} # the html block containing the categories based on user search in string

        return JsonResponse(data=data_dict, safe=False)

    return render(request, 'explore/list.html', {'category' : category,
                                                 'categories' : categories,
                                                 'webpages' : webpages})


thoughts/views.py
from django.shortcuts import render
from .models import Post
from .forms import PostForm
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@csrf_exempt
def post_list(request):
    posts = Post.objects.all().order_by("-publish")
    new_post = None

    # creating a new post
    if request.method == "POST":
        form = PostForm(data=request.POST)

        if form.is_valid():
            try:
                new_post = form.save(commit=False)
                new_post.title = request.POST["title"]
                new_post.author = request.POST["author"]
                new_post.body = request.POST["body"]
                new_post.save()
                return HttpResponse("1")
            except:
                return HttpResponse("Error")
    else:
        form = PostForm()

    return render(request, 'thoughts/post-list.html', {"posts":posts, 'new_post': new_post, 'post_form': form})

website/views.py
from django.shortcuts import render, redirect

def home_view(request):
    return render(request, "home.html")

def index(request):
    return redirect('home/')

def about(request):
    return render(request, "about.html")

def complaints(request):
    return render(request, "complaints.html")

def in_progress(request):
    return render(request, "in-progress.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
<title>Share Anything!</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'bootstrap/superhero.css' %}">
<style>
    /* more than 575px (switching to sidebar) */
    @media screen and (min-width: 576px) {
        .scrollable {
        max-height: 600px;
        overflow-y: auto;
        }
    }

</style>
<!--script for the jquery filter (search)-->
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
</head>

<body>
    {% include "header.html" %}
    {% block content%}{% endblock %}
</body>

<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</html>

templates/complaints.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="padding: 1em">
    <p>
        E-mail: <a href="mailto:leonlong2004@outlook.com">leonlong2004@outlook.com</a>
        <br>
        Tel.: <a href="tel:+4917680843345">+49 17680843345</a>
    </p>
    

</div>

{% endblock %}

templates/explore/list.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid" style="margin-top: 2em;">
    <div class="row flex-xl-nowrap">

        <div class="col-12 col-sm-3 col-mid-3 col-xl-2"> <!-- sidebar-->
            
            <input type="text" placeholder="Search e.g. IB" id="user-input">

            <ul class="nav flex-column">
                <li class="nav-item"><a href="{% url 'explore:webpage_list' %}" class="nav-link {% if not category %}active{% endif %}">All</a></li>
                <div id="replaceable-content" class="scrollable">
                    {% include "explore/categories-results-partial.html" %}
                </div>
            </ul>
        </div>

        <div class="scrollable col-12 col-sm-8 col-md-9 col-xl-8"> <!--main-->
            <h3>Showing: {% if category %}{{ category }}{% else %}all{% endif %}</h3>
            <div class="list-group">
                {% for w in webpages %}
                <a href="{{ w.link }}" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ w }}</h5>
                    </div>
                    <p class="mb-1">{{ w.get_description }}</p>
                </a>
                {% endfor %}
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'home' %}">ShareAnything</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Resources</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'explore:webpage_list' %}">Explore websites</a>
                    <a class="dropdown-item" href="{% url 'in-progress' %}">Useful Tools</a>
                    <a class="dropdown-item" href="{% url 'in-progress' %}">Documents</a>
                    <div class="dropdown-divider"></div>
                    <!--a class="dropdown-item" href="{% url 'in-progress' %}">Restricted Area</a-->
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'thoughts:post_list' %}">Share your thoughts</a>
            </li>
            <!--li class="nav-item">
                <a class="nav-link" href="{% url 'in-progress' %}">Games</a>
            </li-->
            <!--li class="nav-item">
                <a class="nav-link" href="{% url 'in-progress' %}">Today's pranks</a>
            </li-->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
        </ul>
    </div>
</nav>
<!--script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-3">Hello!</h1>
    <p class="lead">Welcome to ShareAnything, it might be your first visit, but it won't be your last.</p>
    <hr class="my-4">
    <a type="button" class="btn btn-success btn-lg" href="{% url 'explore:webpage_list_by_category' 'ib-resources' %}">IB Resources</a>
    <a type="button" class="btn btn-danger btn-lg" href="{% url 'explore:webpage_list_by_category' 'ib-questionbank' %}">IB Questionbank</a>
    <p>We are committed to giving directions and creating a welcoming atmosphere for everyone, and everything</p>
    <p>If you don't know what to do, I strongly suggest you <span style="font-weight: bold;">have a look around</span>,</p>
    <p>or click the boring button below. (not recommended)</p>
    <p class="lead">
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#learnmoreModal">
        Learn more
      </button>
      <div class="modal fade" id="learnmoreModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Warning!</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              We will take you to a very boring page, do you still want to proceed?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
              <a href="{% url 'about' %}" type="button" class="btn btn-primary">I'm a boring person, take me there</a>
            </div>
          </div>
        </div>
      </div>
    </p>

    <h3>Come and explore this place!</h3>
    <p>Here we have a <a href="{% url 'explore:webpage_list' %}">list of websites</a>  you might find useful. Regardless of your occupation and interests, I'm sure you'll find something you like.</p>
    <p>You can also try our <a href="{% url 'thoughts:post_list' %}">ShareYourThoughts</a> feature, which allows you to say anything anonymously.</p>
    <p>Currently those are the only features we have, so you might see "in progress" when you click some links on this website. I can promise you that more updates will come!</p>
    <p>Have fun!</p>
</div>
{% endblock %}